name: Setup

description: Sets up the repo for a typical CI job

inputs:
  cache:
    description: Cache the pnpm store
    required: false
    default: true
  # renovate: datasource=node-version depName=node versioning=node
  node-version:
    description: The Node.js version to use
    required: false
    default: 26.10.0
  skip-checkout:
    description: Skip the checkout step if the repo is already checked out
    default: false
    required: false

runs:
  steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      if: ${{ inputs.skip-checkout == 'false' }}
      with:
        persist-credentials: false
    - uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
      env:
        HUSKY: 0
      with:
        cache: ${{ inputs.cache }}
        runtime: node@${{ inputs.node-version }}
  using: composite
