name: 🐛 Lint Rule Bug
description: Report a bug specific to a lint rule provided by Flint

title: "🐛 Bug: [plugin.ruleName] <short description of the bug>"

labels:
  - "type: bug"

body:
  - type: checkboxes
    attributes:
      description: If any of these required steps are not taken, we may not be able to review your issue. Help us to help you!
      label: Bug Report Checklist
      options:
        - label: I am using the latest published version of all Flint packages.
          required: true
        - label: I have [searched for related issues](https://github.com/flint-fyi/flint/issues?q=is%3Aissue) and found none that matched my issue.
          required: true
  - type: dropdown
    id: plugin
    attributes:
      label: Plugin
      description: What plugin does the rule belong to?
      options:
        - Astro
        - Browser
        - Flint
        - JSON
        - JSX
        - Markdown
        - Next
        - Node
        - Nuxt
        - PackageJSON
        - Performance
        - React
        - SolidJS
        - Sorting
        - Spelling
        - TypeScript
        - Vitest
        - Vue
        - YAML
    validations:
      required: true
  - type: textarea
    attributes:
      description: A minimal code sample which demonstrates the issue
      label: Reproduction
      render: TypeScript
    validations:
      required: true
  - type: textarea
    attributes:
      description: What did you expect to happen?
      label: Expected
    validations:
      required: true
  - type: textarea
    attributes:
      description: What happened instead?
      label: Actual
    validations:
      required: true
  - type: textarea
    attributes:
      description: Any additional info you'd like to provide.
      label: Additional Info
