name: 🚀 Lint Rule Feature
description: Request a feature be added to a lint rule provided by Flint

title: "🚀 Feature: [plugin.ruleName] <short description of the feature>"

labels:
  - "type: feature"

body:
  - type: checkboxes
    attributes:
      description: If any of these required steps are not taken, we may not be able to review your issue. Help us to help you!
      label: Feature Request Checklist
      options:
        - label: I am using the latest published version of all Flint packages.
          required: true
        - label: I have [searched for related issues](https://github.com/flint-fyi/flint/issues?q=is%3Aissue) and found none that matched my issue.
          required: true
  - type: dropdown
    id: plugin
    attributes:
      label: Plugin
      description: What plugin does the rule belong to?
      options:
        - Astro
        - Browser
        - Flint
        - JSON
        - JSX
        - Markdown
        - Next
        - Node
        - Nuxt
        - PackageJSON
        - Performance
        - React
        - SolidJS
        - Sorting
        - Spelling
        - TypeScript
        - Vitest
        - Vue
        - YAML
    validations:
      required: true
  - type: textarea
    attributes:
      description: What did you expect to be able to do?
      label: Overview
    validations:
      required: true
  - type: textarea
    attributes:
      description: Any additional info you'd like to provide.
      label: Additional Info
